name: Java CI with Maven + Neon PostgreSQL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATASOURCE_URL: jdbc:postgresql://ep-wandering-fire-ad70zter-pooler.c-2.us-east-1.aws.neon.tech/items-db
      DATASOURCE_USER: neondb_owner
      DATASOURCE_PASSWORD: ${{ secrets.NEON_DB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ems-backend-jar
        path: target/*.jar
